export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  LOAN_CASE: "/loan-case",
  CASH_CASE: "/cash-case",
  SALE_SHEET: "/sale-sheet",
  PURCHASE_SHEET: "/purchase-sheet",
  PRODUCT_SHEET: "/product-sheet",
  PAYMENT_SHEET: "/payment-sheet",
  STOCK_SHEET: "/stock-sheet",
  BOM_SHEET: "/bom-sheet",
  LABOUR_SHEET: "/labour-sheet",
  CUSTOMER_DETAIL: "/customer-detail",
  QUERY_PENDING: "/query-pending",
  MONTHLY_REPORT: "/monthly-report",
  GST_REPORT: "/gst-report",
  SETTINGS: "/settings",
};
